- type: entity
  id: DeepFryerMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: deep fryer machine board
  components:
    - type: Sprite
      state: service
    - type: MachineBoard
      prototype: KitchenDeepFryer
      requirements: # Frontier
        Capacitor: 1 # Frontier stackRequirements<requirements
        MatterBin: 1 # Frontier stackRequirements<requirements
      stackRequirements:
        Steel: 4
        Glass: 2
        Cable: 5
